### ISSUE TITLE
cutlass 3.0

### ISSUE THREAD

**Issue by fecet** [conda-forge/cutlass-feedstock#11]
### Comment:

Cutlass 3.0(3.1) have been released, should we support that?

**Comment by h-vetinari** [comment]
Yeah we should, but it's been stuck, see https://github.com/conda-forge/cutlass-feedstock/pull/9 & https://github.com/conda-forge/cutlass-feedstock/pull/7. I tried a fix for #9, let's see how it goes. Otherwise you're welcome to raise a PR and debug things! :)

**Comment by fecet** [comment]
I'm willing to contribute if I can provide some help :)  But I'm quite new to conda-forge (I just install from it), can/should we use cuda from nvidia's channel?

**Comment by h-vetinari** [comment]
No, we cannot use Nvidia's channel here. But the good thing is that the relevant parts of that channel are now moving to conda-forge anyway. Also, we managed to solve the issues and compilation timeouts, please let us know if anything is off with cutlass 3.1 (though you need CUDA >=12 for our current builds)
